### PR TITLE
Radius configuration for each screen

### PR DESCRIPTION
**Pull request by tokoro10g**
- Corrected transformation and texture matrices in vnc_layer.hpp
- Added radius configuration for each screen in config.hpp

半径の挙動を修正し，各スクリーンに半径を設定できるパラメータを追加しました．

### CODE REVIEW

**Comment by tokoro10g** [comment]
Video:
https://youtu.be/JCn3dl-1KcQ

The radii for the left and right screen are 2.0 and 1.0, respectively.

**Comment by y-fujii** [comment]
Thank you for the PR.

First, `vnc_layer_t::radius` does not affect to the FOV of a screen and alters a screen size in 3D space by design, because ovrvnc always tries to use the optimal pixel density for Oculus Go.  The `radius` parameters actually control *the amount of parallax* (Yes, the variable name is not good...). A pixel density is controlled by another parameter `vnc_layer_t::resolution`, which has the unit [pixels / pi radians] (2560.0 by default, as Carmack suggests: <https://twitter.com/id_aa_carmack/status/975198157838499840>).

I understand that some people want to scale the screen size.  ~~Although an arbitrary transformation of a screen is already possible to modify a `vnc_layer_t::transform` matrix~~ (EDIT: sorry, the matrix is not suitable for changing the size of cylindrical layers), I have not considered how to expose the parameters in a configuration file yet.  Additionally, mipmaps should be generated if we implement custom scaling.

**Comment by tokoro10g** [comment]
Thank you for the comment! Now I understand what is done with your code (and yes, please do consider renaming...). Sorry for bothering you as I didn't know such details on computer graphics.

I need this feature because I feel the screen is too near, and I have to look around and be exhausted. I close this PR for now, but it would be great if we can implement this in proper way.

Anyway, thanks for the excellent project, and I look forward to the future updates!

**Comment by y-fujii** [comment]
Just reducing a desktop resolution isn't possible?  I think scaling on a client side is generally a bad idea (This is one of the reasons I hesitate to expose a scaling parameter).

I just remove `vnc_layer_t::radius` at 0efd7dda95c2fd95aacd12e0f9e71af5e71f4c30. It is a redundant parameter of an isotropic scaling part of `transform`.  If `transform` is an identity matrix, the cylinder radius is 1.0 [m] after this commit.  Again, scaling matrix does not change the angle of the screen from the center, but it changes the amount of parallax.

By the way, may I introduce your movie on the top page of ovrvnc?  I read your twitter and your attempt (both client and server are running in Oculus Go) is very interesting.

**Comment by y-fujii** [comment]
Implemened in [pixel_scaling](/y-fujii/ovrvnc/tree/pixel_scaling) branch.
It adds the `pixel_scaling` configuration parameter, which scales a screen size and still keeps the distance from origin 10m. It means differently scaled screens are placed on the same cylindrical surface.

**Comment by tokoro10g** [comment]
> Just reducing a desktop resolution isn't possible?

Yes, it helps in some cases, but I also want to connect to an existing X window session via VNC where the resolution is fixed to that of the physical monitor.

> Implemented in pixel_scaling branch.

Thanks! It works like a charm even I'm posting this comment comfortably using ovrvnc!

> By the way, may I introduce your movie on the top page of ovrvnc?

It is a great honor for me; although my fork contains some dirty hacks and tweaks to support keyboard input and recentering. I will write some blog posts about it, so it would be great if you can also refer to the articles.

**Pull request closed without merging**
